name: Build and Deploy Frontend + Signaling Server

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # -----------------------------
      # Build and deploy static frontend
      # -----------------------------
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy Frontend to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_BEACH_048E10F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          output_location: "dist"

      # -----------------------------
      # Build and deploy signaling server
      # -----------------------------
      - name: Build Signaling Server
        run: |
          cd signaling
          npm install
          npm run build

      - name: Deploy Signaling Server to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "kayo-engine-signaling"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./signaling"
